name: Tests
on: [ push, pull_request ]
env:
  APP_ENV: testing
jobs:
    tests:
        name: PHP unit tests
        runs-on: ubuntu-latest
        container: ucraft/php-fpm:8.1.7-x86_64-1

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install dependencies with Composer
                uses: ramsey/composer-install@v2

            -   name: Tests
                run: composer test
